#include "buttons.hpp"

///////////////////////////////////////////////////////////////////////////////
// PRIVATE GLOBALS
///////////////////////////////////////////////////////////////////////////////

adc_oneshot_unit_handle_t adc_handle;

///////////////////////////////////////////////////////////////////////////////
// FUNCTIONS
///////////////////////////////////////////////////////////////////////////////

void buttonsInit() {
    static const char* TAG = "Buttons";

    // Initialize ADC Oneshot Mode Driver on the ADC Unit
    adc_oneshot_unit_init_cfg_t init_config = {
        .unit_id = ADC_UNIT,
        .clk_src = ADC_RTC_CLK_SRC_DEFAULT,
    };
    ESP_ERROR_CHECK(adc_oneshot_new_unit(&init_config, &adc_handle));

    // Configure ADC channel
    adc_oneshot_chan_cfg_t config = {
        .atten = ADC_ATTEN,
        .bitwidth = ADC_BITWIDTH,
    };
    ESP_ERROR_CHECK(adc_oneshot_config_channel(adc_handle, ADC_PIN, &config));

    ESP_LOGI(TAG, "ADC set up successfully");
}


// button_t getPressedButton() {
//     // int adc_value;
//     // ESP_ERROR_CHECK(adc_oneshot_read(adc_handle, ADC_PIN, &adc_value));
    
//     // if (isInRange(adc_value, static_cast<int>(button_t::EVT_BUTTON_SCROLL_D))) {
//     //     return button_t::EVT_BUTTON_SCROLL_D;
//     // } else if (isInRange(adc_value, static_cast<int>(button_t::EVT_BUTTON_SCROLL_U))) {
//     //     return button_t::EVT_BUTTON_SCROLL_U;
//     // } else if (isInRange(adc_value, static_cast<int>(button_t::EVT_BUTTON_BACK))) {
//     //     return button_t::EVT_BUTTON_BACK;
//     // } else if (isInRange(adc_value, static_cast<int>(button_t::EVT_BUTTON_SELECT))) {
//     //     return button_t::EVT_BUTTON_SELECT;
//     // } 
    
//     // return button_t::EVT_NO_BUTTON_PRESSED;

//     const int samples = 20;
//     const int delayMs = 5;

//     int sum = 0;

//     for (int i = 0; i < samples; i++) {
//         int raw;
//         adc_oneshot_read(adc_handle, ADC_PIN, &raw);
//         sum += raw;
//         vTaskDelay(pdMS_TO_TICKS(delayMs));
//     }

//     int avg = sum / samples;

//     if (isInRange(avg, static_cast<int>(button_t::EVT_BUTTON_SCROLL_D))) {
//         return button_t::EVT_BUTTON_SCROLL_D;
//     } else if (isInRange(avg, static_cast<int>(button_t::EVT_BUTTON_SCROLL_U))) {
//         return button_t::EVT_BUTTON_SCROLL_U;
//     } else if (isInRange(avg, static_cast<int>(button_t::EVT_BUTTON_BACK))) {
//         return button_t::EVT_BUTTON_BACK;
//     } else if (isInRange(avg, static_cast<int>(button_t::EVT_BUTTON_SELECT))) {
//         return button_t::EVT_BUTTON_SELECT;
//     }

//     return button_t::EVT_NO_BUTTON_PRESSED;
// }

// ! TODO: This was generated by AI. Need to implement myself.
button_t getPressedButton() {
    constexpr int samples = 20;
    constexpr int delayMs = 5;
    constexpr TickType_t holdTime = pdMS_TO_TICKS(300);
    constexpr TickType_t releaseTime = pdMS_TO_TICKS(50);

    static button_t candidateButton = button_t::EVT_NO_BUTTON_PRESSED;
    static button_t registeredButton = button_t::EVT_NO_BUTTON_PRESSED;

    static TickType_t candidateSince = 0;
    static TickType_t releasedSince = 0;
    static bool releaseTiming = false;

    int sum = 0;

    for (int i = 0; i < samples; i++) {
        int raw = 0;
        ESP_ERROR_CHECK(adc_oneshot_read(adc_handle, ADC_PIN, &raw));

        sum += raw;
        vTaskDelay(pdMS_TO_TICKS(delayMs));
    }

    const int average = sum / samples;
    button_t measuredButton = button_t::EVT_NO_BUTTON_PRESSED;

    if (isInRange(average, static_cast<int>(button_t::EVT_BUTTON_SCROLL_D))) {
        measuredButton = button_t::EVT_BUTTON_SCROLL_D;
    } else if (isInRange(average, static_cast<int>(button_t::EVT_BUTTON_SCROLL_U))) {
        measuredButton = button_t::EVT_BUTTON_SCROLL_U;
    } else if (isInRange(average, static_cast<int>(button_t::EVT_BUTTON_BACK))) {
        measuredButton = button_t::EVT_BUTTON_BACK;
    } else if (isInRange(average, static_cast<int>(button_t::EVT_BUTTON_SELECT))) {
        measuredButton = button_t::EVT_BUTTON_SELECT;
    }

    const TickType_t now = xTaskGetTickCount();

    // Wait for the currently registered button to be released.
    if (registeredButton != button_t::EVT_NO_BUTTON_PRESSED) {
        if (measuredButton == button_t::EVT_NO_BUTTON_PRESSED) {
            if (!releaseTiming) {
                releasedSince = now;
                releaseTiming = true;
            } else if ((now - releasedSince) >= releaseTime) {
                registeredButton = button_t::EVT_NO_BUTTON_PRESSED;
                candidateButton = button_t::EVT_NO_BUTTON_PRESSED;
                releaseTiming = false;
            }
        } else {
            releaseTiming = false;
        }

        return button_t::EVT_NO_BUTTON_PRESSED;
    }

    // No button is currently pressed.
    if (measuredButton == button_t::EVT_NO_BUTTON_PRESSED) {
        candidateButton = button_t::EVT_NO_BUTTON_PRESSED;
        candidateSince = 0;
        return button_t::EVT_NO_BUTTON_PRESSED;
    }

    // A new button press has started.
    if (measuredButton != candidateButton) {
        candidateButton = measuredButton;
        candidateSince = now;
        return button_t::EVT_NO_BUTTON_PRESSED;
    }

    // Register the button only after it has been held long enough.
    if ((now - candidateSince) >= holdTime) {
        registeredButton = candidateButton;
        return registeredButton;
    }

    return button_t::EVT_NO_BUTTON_PRESSED;
}


bool isInRange(int measured_value, int expected_value) {
    // ! If the tolerance is increased, buttons may overlap
    int tolerance = 100;
    
    if ( ((expected_value - tolerance) <= measured_value) && 
        (measured_value <= (expected_value + tolerance)) ) {
        return true;
    }

    return false;
}